use super::cartridge::Error;

#[derive(Debug, PartialEq, Eq)]
pub enum Licensee {
    None,
    Old(&'static str),
    New(&'static str),
}

impl TryFrom<u8> for Licensee {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x00 => Ok(Licensee::None),
            0x01 => Ok(Licensee::Old("Nintendo")),
            0x08 => Ok(Licensee::Old("Capcom")),
            0x09 => Ok(Licensee::Old("HOT-B")),
            0x0A => Ok(Licensee::Old("Jaleco")),
            0x0B => Ok(Licensee::Old("Coconuts Japan")),
            0x0C => Ok(Licensee::Old("Elite Systems")),
            0x13 => Ok(Licensee::Old("EA (Electronic Arts)")),
            0x18 => Ok(Licensee::Old("Hudson Soft")),
            0x19 => Ok(Licensee::Old("ITC Entertainment")),
            0x1A => Ok(Licensee::Old("Yanoman")),
            0x1D => Ok(Licensee::Old("Japan Clary")),
            0x1F => Ok(Licensee::Old("Virgin Games Ltd.3")),
            0x24 => Ok(Licensee::Old("PCM Complete")),
            0x25 => Ok(Licensee::Old("San-X")),
            0x28 => Ok(Licensee::Old("Kemco")),
            0x29 => Ok(Licensee::Old("SETA Corporation")),
            0x30 => Ok(Licensee::Old("Infogrames5")),
            0x31 => Ok(Licensee::Old("Nintendo")),
            0x32 => Ok(Licensee::Old("Bandai")),
            // 0x33 (reserved) indicates to use new licensee
            0x34 => Ok(Licensee::Old("Konami")),
            0x35 => Ok(Licensee::Old("HectorSoft")),
            0x38 => Ok(Licensee::Old("Capcom")),
            0x39 => Ok(Licensee::Old("Banpresto")),
            0x3C => Ok(Licensee::Old(".Entertainment i")),
            0x3E => Ok(Licensee::Old("Gremlin")),
            0x41 => Ok(Licensee::Old("Ubi Soft1")),
            0x42 => Ok(Licensee::Old("Atlus")),
            0x44 => Ok(Licensee::Old("Malibu Interactive")),
            0x46 => Ok(Licensee::Old("Angel")),
            0x47 => Ok(Licensee::Old("Spectrum Holoby")),
            0x49 => Ok(Licensee::Old("Irem")),
            0x4A => Ok(Licensee::Old("Virgin Games Ltd.3")),
            0x4D => Ok(Licensee::Old("Malibu Interactive")),
            0x4F => Ok(Licensee::Old("U.S. Gold")),
            0x50 => Ok(Licensee::Old("Absolute")),
            0x51 => Ok(Licensee::Old("Acclaim Entertainment")),
            0x52 => Ok(Licensee::Old("Activision")),
            0x53 => Ok(Licensee::Old("Sammy USA Corporation")),
            0x54 => Ok(Licensee::Old("GameTek")),
            0x55 => Ok(Licensee::Old("Park Place")),
            0x56 => Ok(Licensee::Old("LJN")),
            0x57 => Ok(Licensee::Old("Matchbox")),
            0x59 => Ok(Licensee::Old("Milton Bradley Company")),
            0x5A => Ok(Licensee::Old("Mindscape")),
            0x5B => Ok(Licensee::Old("Romstar")),
            0x5C => Ok(Licensee::Old("Naxat Soft13")),
            0x5D => Ok(Licensee::Old("Tradewest")),
            0x60 => Ok(Licensee::Old("Titus Interactive")),
            0x61 => Ok(Licensee::Old("Virgin Games Ltd.3")),
            0x67 => Ok(Licensee::Old("Ocean Software")),
            0x69 => Ok(Licensee::Old("EA (Electronic Arts)")),
            0x6E => Ok(Licensee::Old("Elite Systems")),
            0x6F => Ok(Licensee::Old("Electro Brain")),
            0x70 => Ok(Licensee::Old("Infogrames5")),
            0x71 => Ok(Licensee::Old("Interplay Entertainment")),
            0x72 => Ok(Licensee::Old("Broderbund")),
            0x73 => Ok(Licensee::Old("Sculptured Software6")),
            0x75 => Ok(Licensee::Old("The Sales Curve Limited7")),
            0x78 => Ok(Licensee::Old("THQ")),
            0x79 => Ok(Licensee::Old("Accolade")),
            0x7A => Ok(Licensee::Old("Triffix Entertainment")),
            0x7C => Ok(Licensee::Old("Microprose")),
            0x7F => Ok(Licensee::Old("Kemco")),
            0x80 => Ok(Licensee::Old("Misawa Entertainment")),
            0x83 => Ok(Licensee::Old("Lozc")),
            0x86 => Ok(Licensee::Old("Tokuma Shoten")),
            0x8B => Ok(Licensee::Old("Bullet-Proof Software2")),
            0x8C => Ok(Licensee::Old("Vic Tokai")),
            0x8E => Ok(Licensee::Old("Ape")),
            0x8F => Ok(Licensee::Old("I'Max")),
            0x91 => Ok(Licensee::Old("Chunsoft Co.8")),
            0x92 => Ok(Licensee::Old("Video System")),
            0x93 => Ok(Licensee::Old("Tsubaraya Productions")),
            0x95 => Ok(Licensee::Old("Varie")),
            0x96 => Ok(Licensee::Old("Yonezawa/S’Pal")),
            0x97 => Ok(Licensee::Old("Kemco")),
            0x99 => Ok(Licensee::Old("Arc")),
            0x9A => Ok(Licensee::Old("Nihon Bussan")),
            0x9B => Ok(Licensee::Old("Tecmo")),
            0x9C => Ok(Licensee::Old("Imagineer")),
            0x9D => Ok(Licensee::Old("Banpresto")),
            0x9F => Ok(Licensee::Old("Nova")),
            0xA1 => Ok(Licensee::Old("Hori Electric")),
            0xA2 => Ok(Licensee::Old("Bandai")),
            0xA4 => Ok(Licensee::Old("Konami")),
            0xA6 => Ok(Licensee::Old("Kawada")),
            0xA7 => Ok(Licensee::Old("Takara")),
            0xA9 => Ok(Licensee::Old("Technos Japan")),
            0xAA => Ok(Licensee::Old("Broderbund")),
            0xAC => Ok(Licensee::Old("Toei Animation")),
            0xAD => Ok(Licensee::Old("Toho")),
            0xAF => Ok(Licensee::Old("Namco")),
            0xB0 => Ok(Licensee::Old("Acclaim Entertainment")),
            0xB1 => Ok(Licensee::Old("ASCII Corporation or Nexsoft")),
            0xB2 => Ok(Licensee::Old("Bandai")),
            0xB4 => Ok(Licensee::Old("Square Enix")),
            0xB6 => Ok(Licensee::Old("HAL Laboratory")),
            0xB7 => Ok(Licensee::Old("SNK")),
            0xB9 => Ok(Licensee::Old("Pony Canyon")),
            0xBA => Ok(Licensee::Old("Culture Brain")),
            0xBB => Ok(Licensee::Old("Sunsoft")),
            0xBD => Ok(Licensee::Old("Sony Imagesoft")),
            0xBF => Ok(Licensee::Old("Sammy Corporation")),
            0xC0 => Ok(Licensee::Old("Taito")),
            0xC2 => Ok(Licensee::Old("Kemco")),
            0xC3 => Ok(Licensee::Old("Square")),
            0xC4 => Ok(Licensee::Old("Tokuma Shoten")),
            0xC5 => Ok(Licensee::Old("Data East")),
            0xC6 => Ok(Licensee::Old("Tonkinhouse")),
            0xC8 => Ok(Licensee::Old("Koei")),
            0xC9 => Ok(Licensee::Old("UFL")),
            0xCA => Ok(Licensee::Old("Ultra")),
            0xCB => Ok(Licensee::Old("Vap")),
            0xCC => Ok(Licensee::Old("Use Corporation")),
            0xCD => Ok(Licensee::Old("Meldac")),
            0xCE => Ok(Licensee::Old("Pony Canyon")),
            0xCF => Ok(Licensee::Old("Angel")),
            0xD0 => Ok(Licensee::Old("Taito")),
            0xD1 => Ok(Licensee::Old("Sofel")),
            0xD2 => Ok(Licensee::Old("Quest")),
            0xD3 => Ok(Licensee::Old("Sigma Enterprises")),
            0xD4 => Ok(Licensee::Old("ASK Kodansha Co.")),
            0xD6 => Ok(Licensee::Old("Naxat Soft13")),
            0xD7 => Ok(Licensee::Old("Copya System")),
            0xD9 => Ok(Licensee::Old("Banpresto")),
            0xDA => Ok(Licensee::Old("Tomy")),
            0xDB => Ok(Licensee::Old("LJN")),
            0xDD => Ok(Licensee::Old("NCS")),
            0xDE => Ok(Licensee::Old("Human")),
            0xDF => Ok(Licensee::Old("Altron")),
            0xE0 => Ok(Licensee::Old("Jaleco")),
            0xE1 => Ok(Licensee::Old("Towa Chiki")),
            0xE2 => Ok(Licensee::Old("Yutaka")),
            0xE3 => Ok(Licensee::Old("Varie")),
            0xE5 => Ok(Licensee::Old("Epcoh")),
            0xE7 => Ok(Licensee::Old("Athena")),
            0xE8 => Ok(Licensee::Old("Asmik Ace Entertainment")),
            0xE9 => Ok(Licensee::Old("Natsume")),
            0xEA => Ok(Licensee::Old("King Records")),
            0xEB => Ok(Licensee::Old("Atlus")),
            0xEC => Ok(Licensee::Old("Epic/Sony Records")),
            0xEE => Ok(Licensee::Old("IGS")),
            0xF0 => Ok(Licensee::Old("A Wave")),
            0xF3 => Ok(Licensee::Old("Extreme Entertainment")),
            0xFF => Ok(Licensee::Old("LJN")),
            v => Err(Error::InvalidOldLicenseeCode(v)),
        }
    }
}

impl TryFrom<(char, char)> for Licensee {
    type Error = Error;

    fn try_from(value: (char, char)) -> Result<Self, Self::Error> {
        match value {
            ('0', '0') => Ok(Licensee::None),
            ('0', '1') => Ok(Licensee::New("Nintendo R&D1")),
            ('0', '8') => Ok(Licensee::New("Capcom")),
            ('1', '3') => Ok(Licensee::New("Electronic Arts")),
            ('1', '8') => Ok(Licensee::New("Hudson Soft")),
            ('1', '9') => Ok(Licensee::New("b-ai")),
            ('2', '0') => Ok(Licensee::New("kss")),
            ('2', '2') => Ok(Licensee::New("pow")),
            ('2', '4') => Ok(Licensee::New("PCM Complete")),
            ('2', '5') => Ok(Licensee::New("san-x")),
            ('2', '8') => Ok(Licensee::New("Kemco Japan")),
            ('2', '9') => Ok(Licensee::New("seta")),
            ('3', '0') => Ok(Licensee::New("Viacom")),
            ('3', '1') => Ok(Licensee::New("Nintendo")),
            ('3', '2') => Ok(Licensee::New("Bandai")),
            ('3', '3') => Ok(Licensee::New("Ocean/Acclaim")),
            ('3', '4') => Ok(Licensee::New("Konami")),
            ('3', '5') => Ok(Licensee::New("Hector")),
            ('3', '7') => Ok(Licensee::New("Taito")),
            ('3', '8') => Ok(Licensee::New("Hudson")),
            ('3', '9') => Ok(Licensee::New("Banpresto")),
            ('4', '1') => Ok(Licensee::New("Ubi Soft")),
            ('4', '2') => Ok(Licensee::New("Atlus")),
            ('4', '4') => Ok(Licensee::New("Malibu")),
            ('4', '6') => Ok(Licensee::New("angel")),
            ('4', '7') => Ok(Licensee::New("Bullet-Proof")),
            ('4', '9') => Ok(Licensee::New("irem")),
            ('5', '0') => Ok(Licensee::New("Absolute")),
            ('5', '1') => Ok(Licensee::New("Acclaim")),
            ('5', '2') => Ok(Licensee::New("Activision")),
            ('5', '3') => Ok(Licensee::New("American sammy")),
            ('5', '4') => Ok(Licensee::New("Konami")),
            ('5', '5') => Ok(Licensee::New("Hi tech entertainment")),
            ('5', '6') => Ok(Licensee::New("LJN")),
            ('5', '7') => Ok(Licensee::New("Matchbox")),
            ('5', '8') => Ok(Licensee::New("Mattel")),
            ('5', '9') => Ok(Licensee::New("Milton Bradley")),
            ('6', '0') => Ok(Licensee::New("Titus")),
            ('6', '1') => Ok(Licensee::New("Virgin")),
            ('6', '4') => Ok(Licensee::New("LucasArts")),
            ('6', '7') => Ok(Licensee::New("Ocean")),
            ('6', '9') => Ok(Licensee::New("Electronic Arts")),
            ('7', '0') => Ok(Licensee::New("Infogrames")),
            ('7', '1') => Ok(Licensee::New("Interplay")),
            ('7', '2') => Ok(Licensee::New("Broderbund")),
            ('7', '3') => Ok(Licensee::New("sculptured")),
            ('7', '5') => Ok(Licensee::New("sci")),
            ('7', '8') => Ok(Licensee::New("THQ")),
            ('7', '9') => Ok(Licensee::New("Accolade")),
            ('8', '0') => Ok(Licensee::New("misawa")),
            ('8', '3') => Ok(Licensee::New("lozc")),
            ('8', '6') => Ok(Licensee::New("Tokuma Shoten Intermedia")),
            ('8', '7') => Ok(Licensee::New("Tsukuda Original")),
            ('9', '1') => Ok(Licensee::New("Chunsoft")),
            ('9', '2') => Ok(Licensee::New("Video system")),
            ('9', '3') => Ok(Licensee::New("Ocean/Acclaim")),
            ('9', '5') => Ok(Licensee::New("Varie")),
            ('9', '6') => Ok(Licensee::New("Yonezawa/s'pal")),
            ('9', '7') => Ok(Licensee::New("Kaneko")),
            ('9', '9') => Ok(Licensee::New("Pack in soft")),
            ('A', '4') => Ok(Licensee::New("Konami (Yu-Gi-Oh!)")),
            (a, b) => Err(Error::InvalidNewLicenseeCode(a, b)),
        }
    }
}
